# Generated by Django 5.2.6 on 2025-11-15 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_code', models.CharField(max_length=64, unique=True)),
                ('transaction_id', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='COP', max_length=8)),
                ('buyer_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gateway', models.CharField(default='PayU', max_length=32)),
            ],
            options={
                'db_table': 'payments_payment_transaction',
            },
        ),
    ]
