# Generated by Django 5.2.6 on 2025-10-27 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='paymenttransaction',
            table='payments_payment_transaction',
        ),
    ]
