# Generated by Django 5.2.6 on 2025-11-15 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del departamento', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'events_department',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EventChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(help_text='Tipo de cambio: nombre, fecha, estado, etc.', max_length=50)),
                ('field_changed', models.CharField(help_text='Campo modificado', max_length=50)),
                ('old_value', models.TextField(blank=True, help_text='Valor anterior', null=True)),
                ('new_value', models.TextField(blank=True, help_text='Nuevo valor', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del cambio')),
            ],
            options={
                'verbose_name': 'Event Change Log',
                'verbose_name_plural': 'Event Change Logs',
                'db_table': 'events_change_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1, help_text='Number of tickets purchased.')),
                ('date_of_purchase', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('comprada', 'Comprada'), ('usada', 'Usada'), ('pendiente', 'Pendiente por pagar'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('unique_code', models.CharField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'ticket per user',
                'verbose_name_plural': 'Tickets per users',
                'db_table': 'events_ticket',
            },
        ),
        migrations.CreateModel(
            name='TicketAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_time', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('device_info', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'events_ticket_access_log',
            },
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, help_text='Benefits or details of ticket type.')),
            ],
            options={
                'verbose_name': 'Ticket type',
                'verbose_name_plural': 'Ticket Types',
                'db_table': 'events_ticket_type',
            },
        ),
        migrations.CreateModel(
            name='TicketTypeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Specfic price for this event.', max_digits=10)),
                ('maximun_capacity', models.PositiveIntegerField(help_text='Maximun capacity for this event.')),
                ('capacity_sold', models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Settings of ticket type per event',
                'db_table': 'events_ticket_type_event',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la ciudad', max_length=100)),
                ('department', models.ForeignKey(help_text='Departamento al que pertenece la ciudad', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='eventos.department')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'db_table': 'events_city',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField(help_text='Fecha principal del evento (legacy, usar start_datetime y end_datetime)')),
                ('start_datetime', models.DateTimeField(blank=True, help_text='Fecha y hora de inicio del evento', null=True)),
                ('end_datetime', models.DateTimeField(blank=True, help_text='Fecha y hora de finalización del evento', null=True)),
                ('country', models.CharField(default='Colombia', help_text='País donde se realiza el evento', max_length=50)),
                ('city_text', models.CharField(blank=True, help_text='Ciudad libre (otros países)', max_length=100, null=True)),
                ('department_text', models.CharField(blank=True, help_text='Departamento/Región libre (otros países)', max_length=100, null=True)),
                ('status', models.CharField(choices=[('programado', 'Programado'), ('activo', 'Activo'), ('cancelado', 'Cancelado'), ('finalizado', 'Finalizado')], default='programado', max_length=50)),
                ('category', models.CharField(choices=[('musica', 'Música'), ('deporte', 'Deporte'), ('educacion', 'Educación'), ('tecnologia', 'Tecnología'), ('arte', 'Arte'), ('otros', 'Otros')], default='otros', help_text='Categoría del evento', max_length=50)),
                ('image', models.URLField(blank=True, help_text='URL de la imagen del evento (almacenada en Supabase)', null=True)),
                ('organizer', models.CharField(blank=True, help_text='Nombre del organizador', max_length=200, null=True)),
                ('min_age', models.PositiveIntegerField(blank=True, help_text='Edad mínima requerida para asistir al evento. Dejar vacío si no hay restricción.', null=True)),
                ('max_capacity', models.PositiveIntegerField(blank=True, help_text='Aforo máximo permitido para el evento.', null=True)),
                ('sales_open_datetime', models.DateTimeField(blank=True, help_text='Fecha y hora en que se habilitan las ventas de tickets.', null=True)),
                ('location', models.ForeignKey(blank=True, help_text='Ciudad del evento (solo Colombia)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.city')),
            ],
            options={
                'db_table': 'events_event',
                'permissions': [('cancelar_evento', 'Puede cancelar evento'), ('inscribirse_evento', 'Puede inscribirse a un evento')],
            },
        ),
    ]
