# Generated by Django 5.2.6 on 2025-10-07 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('activo', 'Activo'), ('cancelado', 'Cancelado')], default='activo', max_length=520)),
            ],
            options={
                'permissions': [('cancelar_evento', 'Puede cancelar evento'), ('inscribirse_evento', 'Puede inscribirse a un evento')],
            },
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, help_text='Benefits or details of ticket type.')),
            ],
            options={
                'verbose_name': 'Ticket type',
                'verbose_name_plural': 'Ticket Types',
            },
        ),
        migrations.CreateModel(
            name='TicketTypeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Specfic price for this event.', max_digits=10)),
                ('maximun_capacity', models.PositiveIntegerField(help_text='Maximun capacity for this event.')),
                ('capacity_sold', models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Settings of ticket type per event',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1, help_text='Number of tickets purchased.')),
                ('date_of_purchase', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('comprada', 'Comprada'), ('usada', 'Usada'), ('cancelada', 'Cancelada')], default='comprada', max_length=20)),
                ('unique_code', models.CharField(blank=True, max_length=100, unique=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='eventos.event')),
            ],
            options={
                'verbose_name': 'ticket per user',
                'verbose_name_plural': 'Tickets per users',
            },
        ),
    ]
