# Generated by Django 5.2.6 on 2025-09-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                ("fecha", models.DateField()),
                ("ubicacion", models.CharField(max_length=200)),
                ("cantidad_asistentes", models.PositiveIntegerField()),
                (
                    "precio_entrada",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
        ),
    ]
