# Generated by Django 5.2.6 on 2025-09-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="evento",
            options={
                "permissions": [
                    ("cancelar_evento", "Puede cancelar evento"),
                    ("modificar_evento", "Puede modificar evento"),
                    ("unirse_evento", "Puede unirse a evento"),
                ]
            },
        ),
        migrations.RenameField(
            model_name="evento",
            old_name="cantidad_asistentes",
            new_name="aforo",
        ),
        migrations.RenameField(
            model_name="evento",
            old_name="precio_entrada",
            new_name="precio",
        ),
        migrations.AddField(
            model_name="evento",
            name="estado",
            field=models.CharField(
                choices=[("activo", "Activo"), ("cancelado", "Cancelado")],
                default="activo",
                max_length=520,
            ),
        ),
    ]
