# Generated by Django 5.2.6 on 2025-11-15 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventchangelog',
            name='changed_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó el cambio', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventchangelog',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='eventos.event'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='eventos.event'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketaccesslog',
            name='accessed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketaccesslog',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='eventos.ticket'),
        ),
        migrations.AddField(
            model_name='tickettypeevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.event'),
        ),
        migrations.AddField(
            model_name='tickettypeevent',
            name='ticket_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.tickettype'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='config_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.tickettypeevent'),
        ),
        migrations.AddField(
            model_name='event',
            name='types_of_tickets_available',
            field=models.ManyToManyField(blank=True, related_name='event', through='eventos.TicketTypeEvent', to='eventos.tickettype'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'department')},
        ),
        migrations.AlterUniqueTogether(
            name='tickettypeevent',
            unique_together={('event', 'ticket_type')},
        ),
    ]
