# Generated by Django 5.2.6 on 2025-10-07 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tickettypeevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.event'),
        ),
        migrations.AddField(
            model_name='tickettypeevent',
            name='ticket_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.tickettype'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='config_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.tickettypeevent'),
        ),
        migrations.AddField(
            model_name='event',
            name='types_of_tickets_available',
            field=models.ManyToManyField(blank=True, related_name='event', through='eventos.TicketTypeEvent', to='eventos.tickettype'),
        ),
        migrations.AlterUniqueTogether(
            name='tickettypeevent',
            unique_together={('event', 'ticket_type')},
        ),
    ]
