# Generated by Django 5.2.6 on 2025-09-12 20:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0002_alter_evento_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="inscritos",
            field=models.ManyToManyField(
                blank=True,
                related_name="eventos_inscritos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
