# Generated by Django 5.2.6 on 2025-11-15 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('musica', 'Música'), ('deporte', 'Deporte'), ('educacion', 'Educación'), ('tecnologia', 'Tecnología'), ('arte', 'Arte'), ('otros', 'Otros')], default='otros', help_text='Categoría del evento', max_length=50),
        ),
    ]
