# Generated by Django 5.2.6 on 2025-10-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('comprada', 'Comprada'), ('usada', 'Usada'), ('pendiente', 'Pendiente por pagar'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
    ]
