# Generated by Django 5.2.6 on 2025-09-20 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_evento_inscritos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'permissions': [('cancelar_evento', 'Puede cancelar evento'), ('inscribirse_evento', 'Puede inscribirse a un evento')]},
        ),
    ]
