# Generated by Django 5.2.6 on 2025-11-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_alter_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('programado', 'Programado'), ('activo', 'Activo'), ('cancelado', 'Cancelado'), ('finalizado', 'Finalizado')], default='programado', help_text='Categoría del evento', max_length=50),
        ),
    ]
