# Generated by Django 5.2.6 on 2025-10-27 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_departamento_alter_event_city_alter_event_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='city_obj',
            field=models.ForeignKey(blank=True, help_text='Ciudad (solo Colombia)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.ciudad'),
        ),
        migrations.AddField(
            model_name='event',
            name='city_text',
            field=models.CharField(blank=True, help_text='Ciudad libre (otros países)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='department_obj',
            field=models.ForeignKey(blank=True, help_text='Departamento (solo Colombia)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.departamento'),
        ),
        migrations.AddField(
            model_name='event',
            name='department_text',
            field=models.CharField(blank=True, help_text='Departamento/Región libre (otros países)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(help_text='Ciudad del evento (solo Colombia)', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='department',
            field=models.CharField(help_text='Departamento del evento (solo Colombia)', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.URLField(blank=True, help_text='URL de la imagen del evento (almacenada en Supabase)', null=True),
        ),
    ]
