# Generated by Django 5.2.6 on 2025-11-24 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_event_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
    ]
