# Generated by Django 5.2.6 on 2025-10-27 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_event_city_obj_event_city_text_event_department_obj_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la ciudad', max_length=100)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del departamento', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='ciudad',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='ciudad',
            name='departamento',
        ),
        migrations.AlterField(
            model_name='event',
            name='city_obj',
            field=models.ForeignKey(blank=True, help_text='Ciudad (solo Colombia)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.city'),
        ),
        migrations.AddField(
            model_name='city',
            name='department',
            field=models.ForeignKey(help_text='Departamento al que pertenece la ciudad', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='eventos.department'),
        ),
        migrations.AlterField(
            model_name='event',
            name='department_obj',
            field=models.ForeignKey(blank=True, help_text='Departamento (solo Colombia)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.department'),
        ),
    ]
