# Generated by Django 5.2.6 on 2025-10-27 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_city_department_alter_ciudad_unique_together_and_more'),
        ('usuarios', '0006_documenttype_alter_customuser_city_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ciudad',
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'department')},
        ),
        migrations.DeleteModel(
            name='Departamento',
        ),
    ]
