# Generated by Django 5.2.6 on 2025-10-27 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_delete_ciudad_alter_city_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='city',
            table='events_city',
        ),
        migrations.AlterModelTable(
            name='department',
            table='events_department',
        ),
        migrations.AlterModelTable(
            name='event',
            table='events_event',
        ),
        migrations.AlterModelTable(
            name='ticket',
            table='events_ticket',
        ),
        migrations.AlterModelTable(
            name='ticketaccesslog',
            table='events_ticketaccesslog',
        ),
        migrations.AlterModelTable(
            name='tickettype',
            table='events_tickettype',
        ),
        migrations.AlterModelTable(
            name='tickettypeevent',
            table='events_tickettypeevent',
        ),
    ]
