# Generated by Django 5.2.6 on 2025-10-27 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0009_alter_city_table_alter_department_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ticketaccesslog',
            table='events_ticket_accesslog',
        ),
        migrations.AlterModelTable(
            name='tickettype',
            table='events_ticket_type',
        ),
        migrations.AlterModelTable(
            name='tickettypeevent',
            table='events_ticket_type_event',
        ),
    ]
