# Generated by Django 5.2.6 on 2025-10-27 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0010_alter_ticketaccesslog_table_alter_tickettype_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='city',
            table=None,
        ),
        migrations.AlterModelTable(
            name='department',
            table=None,
        ),
        migrations.AlterModelTable(
            name='event',
            table=None,
        ),
        migrations.AlterModelTable(
            name='ticket',
            table=None,
        ),
        migrations.AlterModelTable(
            name='ticketaccesslog',
            table='events_ticket_access_log',
        ),
        migrations.AlterModelTable(
            name='tickettype',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tickettypeevent',
            table=None,
        ),
    ]
