# Generated by Django 5.2.6 on 2025-10-28 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0011_alter_city_table_alter_department_table_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='min_age',
            field=models.PositiveIntegerField(blank=True, help_text='Edad mínima requerida para asistir al evento. Dejar vacío si no hay restricción.', null=True),
        ),
        migrations.AlterModelTable(
            name='city',
            table='events_city',
        ),
        migrations.AlterModelTable(
            name='department',
            table='events_department',
        ),
        migrations.AlterModelTable(
            name='tickettype',
            table='events_ticket_type',
        ),
        migrations.CreateModel(
            name='EventChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(help_text='Tipo de cambio: nombre, fecha, estado, etc.', max_length=50)),
                ('field_changed', models.CharField(help_text='Campo modificado', max_length=50)),
                ('old_value', models.TextField(blank=True, help_text='Valor anterior', null=True)),
                ('new_value', models.TextField(blank=True, help_text='Nuevo valor', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del cambio')),
                ('changed_by', models.ForeignKey(blank=True, help_text='Usuario que realizó el cambio', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='eventos.event')),
            ],
            options={
                'verbose_name': 'Event Change Log',
                'verbose_name_plural': 'Event Change Logs',
                'db_table': 'events_change_log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
