# Generated by Django 5.2.6 on 2025-10-29 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0012_event_min_age_alter_city_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='city',
        ),
        migrations.RemoveField(
            model_name='event',
            name='city_obj',
        ),
        migrations.RemoveField(
            model_name='event',
            name='department',
        ),
        migrations.RemoveField(
            model_name='event',
            name='department_obj',
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Ciudad del evento (solo Colombia)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.city'),
        ),
        migrations.AlterField(
            model_name='event',
            name='country',
            field=models.CharField(default='Colombia', help_text='País donde se realiza el evento', max_length=50),
        ),
    ]
