# Generated by Django 5.2.6 on 2025-10-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0013_remove_event_city_remove_event_city_obj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Aforo máximo permitido para el evento.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='sales_open_datetime',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se habilitan las ventas de tickets.', null=True),
        ),
    ]
