# Generated by Django 5.2.6 on 2025-10-30 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0014_event_max_capacity_event_sales_open_datetime'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table='events_event',
        ),
        migrations.AlterModelTable(
            name='ticket',
            table='events_ticket',
        ),
        migrations.AlterModelTable(
            name='tickettypeevent',
            table='events_ticket_type_event',
        ),
    ]
