# Generated by Django 5.2.6 on 2025-11-15 01:02

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del tipo de documento', max_length=50, unique=True)),
                ('code', models.CharField(help_text='Código del tipo de documento', max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Document type',
                'verbose_name_plural': 'Document types',
                'db_table': 'users_document_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(help_text='Nombres', max_length=150)),
                ('last_name', models.CharField(help_text='Apellidos', max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, help_text='Teléfono de contacto', max_length=20, null=True)),
                ('birth_date', models.DateField(blank=True, help_text='Fecha de nacimiento', null=True)),
                ('document', models.CharField(blank=True, help_text='Número de documento', max_length=30, null=True, unique=True)),
                ('country', models.CharField(blank=True, default='Colombia', help_text='País de residencia', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del usuario')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización del usuario')),
                ('city_text', models.CharField(blank=True, help_text='Ciudad libre (otros países)', max_length=100, null=True)),
                ('department_text', models.CharField(blank=True, help_text='Departamento/Región libre (otros países)', max_length=100, null=True)),
                ('is_email_verified', models.BooleanField(default=False, help_text='Indica si el email ha sido verificado')),
                ('city', models.ForeignKey(blank=True, help_text='Ciudad de residencia (solo Colombia)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.city')),
                ('department', models.ForeignKey(blank=True, help_text='Departamento de residencia (solo Colombia)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.department')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('document_type', models.ForeignKey(blank=True, help_text='Tipo de documento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.documenttype')),
            ],
            options={
                'db_table': 'users_custom_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(help_text='Tipo de cambio: email, password, datos personales', max_length=50)),
                ('field_changed', models.CharField(help_text='Campo modificado', max_length=50)),
                ('old_value', models.TextField(blank=True, help_text='Valor anterior', null=True)),
                ('new_value', models.TextField(blank=True, help_text='Nuevo valor', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del cambio')),
                ('changed_by', models.ForeignKey(blank=True, help_text='Usuario que realizó el cambio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_changes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Change Log',
                'verbose_name_plural': 'User Change Logs',
                'db_table': 'users_change_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('token_type', models.CharField(choices=[('email_verification', 'Email Verification'), ('password_reset', 'Password Reset')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_token',
                'indexes': [models.Index(fields=['token', 'token_type'], name='users_token_token_ba8c94_idx')],
            },
        ),
    ]
