# Generated by Django 5.2.6 on 2025-11-21 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Foto de perfil del usuario', null=True, upload_to='profile_pictures/'),
        ),
    ]
