# Generated by Django 5.2.6 on 2025-10-16 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, help_text='Ciudad de residencia', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, default='Colombia', help_text='País de residencia', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='document',
            field=models.CharField(blank=True, help_text='Documento de identidad', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, help_text='Teléfono de contacto', max_length=20, null=True),
        ),
    ]
