# Generated by Django 5.2.6 on 2025-10-16 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_customuser_birth_date_customuser_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de documento',
                'verbose_name_plural': 'Tipos de documento',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-10-16T00:00:00', help_text='Fecha de creación del usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(default='sin nombre', help_text='Nombres', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(default=1, help_text='Apellidos', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de última actualización del usuario'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='document',
            field=models.CharField(blank=True, help_text='Número de documento', max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='document_type',
            field=models.ForeignKey(blank=True, help_text='Tipo de documento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.tipodocumento'),
        ),
    ]
