# Generated by Django 5.2.6 on 2025-10-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_tipodocumento_remove_customuser_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipodocumento',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='tipodocumento',
            name='codigo',
            field=models.CharField(default='GEN', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
