# Generated by Django 5.2.6 on 2025-10-27 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_event_city_obj_event_city_text_event_department_obj_and_more'),
        ('usuarios', '0004_remove_tipodocumento_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='city_text',
            field=models.CharField(blank=True, help_text='Ciudad libre (otros países)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='department_text',
            field=models.CharField(blank=True, help_text='Departamento/Región libre (otros países)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.ForeignKey(blank=True, help_text='Ciudad de residencia (solo Colombia)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.ciudad'),
        ),
    ]
