# Generated by Django 5.2.6 on 2025-10-27 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_city_department_alter_ciudad_unique_together_and_more'),
        ('usuarios', '0005_customuser_city_text_customuser_department_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del tipo de documento', max_length=50, unique=True)),
                ('code', models.CharField(help_text='Número del tipo de documento', max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Document type',
                'verbose_name_plural': 'Document types',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.ForeignKey(blank=True, help_text='Ciudad de residencia (solo Colombia)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.city'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='document_type',
            field=models.ForeignKey(blank=True, help_text='Tipo de documento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.documenttype'),
        ),
        migrations.DeleteModel(
            name='TipoDocumento',
        ),
    ]
