# Generated by Django 5.2.6 on 2025-10-27 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_documenttype_alter_customuser_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='users_custom_user',
        ),
    ]
