# Generated by Django 5.2.6 on 2025-10-27 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_customuser_options_alter_customuser_table'),
        ('usuarios', '0007_rename_usuarios_documenttype'),
    ]

    operations = [
    ]
