# Generated by Django 5.2.6 on 2025-10-28 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0012_event_min_age_alter_city_table_and_more'),
        ('usuarios', '0008_merge_20251027_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Departamento de residencia (solo Colombia)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.department'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text='Indica si el email ha sido verificado'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='code',
            field=models.CharField(help_text='Código del tipo de documento', max_length=10, unique=True),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE IF EXISTS usuarios_documenttype RENAME TO users_document_type;",
                    reverse_sql="ALTER TABLE IF EXISTS users_document_type RENAME TO usuarios_documenttype;",
                ),
            ],
            state_operations=[
                migrations.AlterModelTable(
                    name='documenttype',
                    table='users_document_type',
                ),
            ],
        ),
        migrations.CreateModel(
            name='UserChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(help_text='Tipo de cambio: email, password, datos personales', max_length=50)),
                ('field_changed', models.CharField(help_text='Campo modificado', max_length=50)),
                ('old_value', models.TextField(blank=True, help_text='Valor anterior', null=True)),
                ('new_value', models.TextField(blank=True, help_text='Nuevo valor', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del cambio')),
                ('changed_by', models.ForeignKey(blank=True, help_text='Usuario que realizó el cambio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_changes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Change Log',
                'verbose_name_plural': 'User Change Logs',
                'db_table': 'users_change_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('token_type', models.CharField(choices=[('email_verification', 'Email Verification'), ('password_reset', 'Password Reset')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_token',
                'indexes': [models.Index(fields=['token', 'token_type'], name='users_token_token_ba8c94_idx')],
            },
        ),
    ]
